apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  lables:
    name: result-app-service
    app: demo-votting-app
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: result-app-pod
    app: demo-votting-app